name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   create:
#     tags:
#       - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: cargo build --release --verbose
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: 1.0.${{ github.run_number }}
        tag: refs/heads/release/1.0.${{ github.run_number }}
        artifacts: "target/release/*.exe"
        bodyFile: "README.md"
        token: ${{ secrets.GITHUB_TOKEN }}
