name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install windows toolchain
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustup toolchain install stable-x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu --verbose
    - name: Run tests
      run: cargo test --verbose
